# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2148b4aa395a9d868465e0c327dabfe65f20dbd770a50774c0098aaba53515ce5292d3d94d0d1a9b59901a3c880fadef30f6c146e33fa207d17376f57ff941e4

test:
  secret_key_base: ea3131d59c1f9052bcb338075387b6466450fc1950a8a1c23c9b79187e1d3cd882a5f0db193a6c7244b6c42c6131b823ae7497dfa50276ccc54191b2ac2543de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
